repositories:
  - name: bitnami
    url: https://mirror.yandex.ru/helm/charts.bitnami.com
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
    
environments:
  prod:
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

releases:
  - name: metrics-server
    labels:
      app: metrics-server
    wait: true
    chart: metrics-server/metrics-server
    version: 3.13.0
    values:
      - values-metrics-server.yaml.gotmpl

  - name: ingress-nginx
    labels:
      app: ingress-nginx
    wait: true
    chart: ingress-nginx/ingress-nginx
    # update ingress-nginx version to 1.12.1 for fix CVE-2025-1098
    # https://www.opennet.ru/opennews/art.shtml?num=62946
    version: 4.12.1
    values:
      - values-ingress-nginx.yaml.gotmpl

  - name: cert-manager
    wait: true
    chart: jetstack/cert-manager
    version: 1.14.5
    needs: 
      - ingress-nginx
    values:
      - values-cert-manager.yaml.gotmpl
    # deploy custom resource using hooks feature of helmfile since there is nothing like extraDeploy for this chart
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "sh"
        # envsubst tool is used to replace env variables in file with their values
        args: ["-c", "envsubst < ./cert-manager-cluster-issuer.yaml | kubectl apply -f -"]

  - name: postgresql
    labels:
      app: postgresql
    wait: true
    chart: bitnami/postgresql
    version: 12.2.7
    values:
      - values-postgresql.yaml.gotmpl

  - name: home-cms
    labels:
      app: home-cms
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    # it won't work anyway until ingress controller is created
    # thus we wait for it to be ready first
    needs: 
      - ingress-nginx
      - postgresql
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/home-cms.git@/ci/values.yaml?ref=master
      - values.yaml.gotmpl
      - values-cms.yaml.gotmpl

  - name: home-ui
    labels:
      app: home-ui
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    # it won't work anyway until ingress controller is created
    # thus we wait for it to be ready first
    needs: 
      - ingress-nginx
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/home-ui.git@/ci/values.yaml?ref=master
      - values.yaml.gotmpl
      - values-ui.yaml.gotmpl    
